# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
---
version: 2
updates:
  # Cargo dependencies
  - package-ecosystem: cargo
    directory: /
    schedule: { interval: monthly }
    labels: [dependencies, rust]
    open-pull-requests-limit: 2
    groups: { cargo-dependencies: { patterns: ["*"] } }

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
    labels: [dependencies, github-actions]
    open-pull-requests-limit: 2
    groups: { github-actions: { patterns: ["*"] } }
