# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip: [actionlint, actionlint-docker, actionlint-system]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v0.6.39
    hooks:
      - id: tombi-format
      - id: tombi-lint
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.3.2
    hooks:
      - id: biome-check
  - repo: local
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files
        description: Runs actionlint to lint GitHub Actions workflow files
        language: golang
        types: ["yaml"]
        files: ^\.github/workflows/
        entry: actionlint
        minimum_pre_commit_version: 3.0.0
      # - id: actionlint-docker
      #   name: Lint GitHub Actions workflow files
      #   description: Runs actionlint Docker image to lint GitHub Actions workflow files
      #   language: docker_image
      #   types: ["yaml"]
      #   files: ^\.github/workflows/
      #   entry: docker.io/rhysd/actionlint:1.7.8
      # - id: actionlint-system
      #   name: Lint GitHub Actions workflow files
      #   description: Runs system-installed actionlint to lint GitHub Actions workflow files
      #   language: system
      #   types: ["yaml"]
      #   files: ^\.github/workflows/
      #   entry: actionlint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: [-x]
#  - repo: local
#    hooks:
#    - id: bashate
#      name: bashate
#      description: This hook runs bashate for linting shell scripts
#      entry: bashate
#      language: python
#      types: [shell]
#      args: ['--ignore', 'E002,E003,E006']
  - repo: local
    hooks:
      - id: bun-build
        name: Build proxy.js
        description: Runs `bun run build` to build the project.
        entry: bun run build
        language: system
        files: \.(rs|ts|toml|json)$
        pass_filenames: false
        stages: [pre-commit]
